blank_issues_enabled: false
contact_links:
  - name: Question or Help
    url: https://github.com/KakkoiDev/nihongo-it-anki/discussions
    about: For questions or help, please use Discussions instead of issues.
